### ISSUE TITLE
Storybook loading struck with white screen

### ISSUE THREAD

**Issue by Brad19** [amandeepmittal/hello-tsx-storybook#1]
Hi @amandeepmittal ,

I created a new create-react-app couple of days back and have been configuring various things required for our project. And we're having a requirement to use story book for our project. 
So I was doing a bit of search and then I bumped into your following article to set up the storybook for create-react-app - typescript. 
 https://blog.crowdbotics.com/setup-a-react-app-with-typescript-storybook-and-crowdbotics/ 

I followed from adding a story book till last and when i run the story book with 'yarn storybook'.  I get the following which is ok
![image](https://user-images.githubusercontent.com/10935246/80073158-a812b200-858a-11ea-98c7-916f8fab797c.png)

I see only the white screen in the story book showing something is loading as shown below

![image](https://user-images.githubusercontent.com/10935246/80073212-b9f45500-858a-11ea-9bda-ff90a3ed8732.png)

Not sure where did I go wrong. Please advise

Here is my package.json

{
  "name": "xxx",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@types/jest": "^24.0.0",
    "@types/node": "^12.0.0",
    "@types/react": "^16.9.0",
    "@types/react-dom": "^16.9.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.4.1",
    "typescript": "~3.7.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "lint": "eslint --ext .js,.jsx,.ts,.tsx src --color",
    "format": "prettier --write src/**/*.{ts,tsx,scss,css,json}",
    "isready": "npm run format && npm run lint && npm run build",
    "storybook": "start-storybook -p 9001 -c .storybook"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "description": "",
  "repository": {
    "type": "git",
    "url": "git+ssh://git@bitbucket.org/xxx.git"
  },
  "author": "xxx",
  "license": "ISC",
  "devDependencies": {
    "@babel/core": "7.9.0",
    "@storybook/preset-create-react-app": "2.1.1",
    "@storybook/react": "5.3.18",
    "@types/storybook__react": "5.2.1",
    "@typescript-eslint/eslint-plugin": "2.29.0",
    "@typescript-eslint/parser": "2.29.0",
    "awesome-typescript-loader": "5.2.1",
    "babel-eslint": "10.1.0",
    "babel-loader": "8.1.0",
    "eslint": "6.8.0",
    "eslint-config-airbnb": "18.1.0",
    "eslint-config-airbnb-typescript": "7.2.1",
    "eslint-config-prettier": "6.10.1",
    "eslint-config-react-app": "5.2.1",
    "eslint-import-resolver-typescript": "2.0.0",
    "eslint-loader": "4.0.0",
    "eslint-plugin-flowtype": "4.7.0",
    "eslint-plugin-import": "2.20.2",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-prettier": "3.1.3",
    "eslint-plugin-react": "7.19.0",
    "eslint-plugin-react-hooks": "3.0.0",
    "prettier": "2.0.4",
    "prettier-eslint": "9.0.1",
    "prettier-eslint-cli": "5.0.0",
    "react-docgen-typescript-loader": "3.7.2",
    "react-docgen-typescript-webpack-plugin": "1.1.0"
  }
}

**Comment by Brad19** [comment]
Hi @amandeepmittal ,
Pls don't bother as I've resolved. I did a small mistake where i mistakenly created storybook folder inside src rather than outside and that made all these. Apologies for the inconvenience

**Comment by amandeepmittal** [comment]
Hey @Brad19 I couldn't catch up wit you on this. No inconvenience caused. Thanks for reaching out though and I am glad you have resolved the issue. I am going to close this issue too if you don't mind.
